### ISSUE TITLE
gene selection

### ISSUE THREAD

**Issue by dylanmr** [phillipnicol/scDist#1]
Thanks for the great tool! I was wondering if you had any thoughts regarding the gene selection for input to scDist? I saw in the code for the simulation study you use the scale.data matrix as input for scDist. Would you suggest to loop through all celltypes in a dataset, recalculate HVGs and then running scDist on each celltype individually? Or to simply run scDist on an entire seurat object with a hard coded set of HVGs. 

Thanks!

**Comment by phillipnicol** [comment]
I would recommend the second option because the distance is only comparable between cell types when the same set of genes has been used. I.e., have one set of genes and define a normalized count matrix (across all cell types), and pass that in as the input to scDist.

**Comment by dylanmr** [comment]
thanks for the input! one last question, have you benchmarked how stable the distance calculation is across differing number of genes used?

Thanks again!

**Comment by phillipnicol** [comment]
Not yet, although we did look at how varying the # of PCs used changed distance estimates (Figure S13 in the paper). Throughout the paper we typically used 2000 HVGs selected by Seurat. Because the first step is PCA, I would hope that it is not too sensitive adding or removing genes that contribute a low % of variance explained, but this is definitely an analysis we will consider when we revise the paper. Thanks!
