### ISSUE TITLE
Normalized data or scaled data?

### ISSUE THREAD

**Issue by ShadHOH** [phillipnicol/scDist#2]
Great work on developing this tool. I took notice that you're using the scaled data in the `scDist/Figures/scDist_negative_control.R` script (line 35), although the tool calls for the normalized counts. Since I've been unable to find any scaling flag in the prcomp function within scDist, would it be fair to assume that the scaled data of the normalized counts is the appropriate input?

Thanks

**Comment by phillipnicol** [comment]
Thank you! 

In our analyses we used the scaled data because we did not want genes with high variance (after normalization) to be over-represented in the analysis. This is what we recommend (specifically, we recommended scTransform in equation 5 of Methods) but if there is a reason to prefer unscaled data that can be used as well.

Let me know if this helps!

**Comment by phillipnicol** [comment]
Yes scDist can be applied as long as the cluster labels are shared between the two (or more datasets). If this is the case, then you could try accounting for the different dataset by including an additional effect in the scDist argument `fixed_effects = c(condition, dataset)` where `dataset` is encoded as a factor. This would allow for the baseline expression to vary by dataset, which means that you could try applying scDist to the entire (normalized) count matrix without applying any additional integration methods. This might be preferable since I'm never quite sure how some integration approaches might distort the data.
