### ISSUE TITLE
Multiple testing

### ISSUE THREAD

**Issue by ShadHOH** [phillipnicol/scDist#3]
Hi,

Although scDist successfully returns significance values, I was wondering if you could speak to why multiple testing correction is omitted. Is this a conscious decision, leaving the user with more agency to do the adjustment themselves?

Thanks

**Comment by phillipnicol** [comment]
First, I would recommend using the distance estimate `$results$Dist.` as a way to decide if a cell type is perturbed. The distance estimate has already been shrunken towards 0 to account for the uncertainty. 

In `scDist::FDRDistPlot` we use the FDR corrected p-values instead of the raw p-values. However, we wanted to leave it up to the user what type (if any) of adjustment to make. The cost of a false discovery may not be very high if the goal is to exploratory data analysis. Also, in the small sample/patient case, the power of the mixed-effects model can be low meaning that p-values could be high even if there is true separation (ideally the `Dist.` estimate would pick that up).
