### ISSUE TITLE
Adapt scDist for MiloDE, ideal number of Principal components for few cells

### ISSUE THREAD

**Issue by MaximilianNuber** [phillipnicol/scDist#4]
Dear all,

I am trying to adapt scDist to use it with miloDE (https://www.biorxiv.org/content/10.1101/2023.03.08.531744v1).
MiloDE builds on miloR assigning cells to neighborhoods, and proceeds to find neighborhoods where cells between 2 experimental groups are different. For this purpose, the package includes a function `calc_AUC_per_neighbourhood`, which uses the Augur package with random forest to get the AUC, and therefore the separatability between the two groups within a neighborhood.

Unfortunately, this is computationally intensive and takes too long / crashes for large datasets I analyze. Therefore, I would like to use scDist to calculate the distance between two groups per neighborhood.

I am currently using this dataset to test: https://cellxgene.cziscience.com/e/e067e5ca-e53e-485f-aa8e-efd5435229c8.cxg/

The main question I have, as in the title, is about determining the ideal number of principal components to use.
Important to note: For each neighborhood, the `SingleCellExperiment` is subset to only include cells of one neighborhood.
In the example dataset, this ranges between 30 and a few hundred cells. In any case, testing has shown me that scDist runs faster than Augur for this use case.
For subsetting and checking the validity of a neighborhood I use the functionality present in miloDE.

First, I want to compare the performance of scDist on the entire dataset vs only on one celltype and compare the results.
Using `d=10` I tested for all cell types, as compared to run scDist for only "renal alpha-intercalated cell". The results were only slightly different, therefore I hoped subsetting to a single cell type is a valid approach, and ask here if this is the case in your estimation.
```
meta.data = seu@meta.data[, c("disease", "donor_id", "cell_type")]
out <- scDist(as.matrix(seu[["RNA"]]$data),meta.data,fixed.effects = "disease",
              random.effects="donor_id",
              clusters="cell_type",
              d = 10)
out$results["renal alpha-intercalated cell", ]

# Dist. 95% CI (low) 95% CI (upper)      p.val
# renal alpha-intercalated cell 2.674169            0       4.064603 0.08274917

meta.data = subset(seu, cell_type == "renal alpha-intercalated cell")@meta.data[, c("disease", "donor_id", "cell_type")]
out.renal_alpha <- scDist(as.matrix(subset(seu, cell_type == "renal alpha-intercalated cell")[["RNA"]]$data),
              meta.data,fixed.effects = "disease",
              random.effects="donor_id",
              clusters="cell_type",
              d = 10)
out.renal_alpha$results
## Dist. 95% CI (low) 95% CI (upper)      p.val
## renal alpha-intercalated cell 2.676443            0       4.048841 0.08262917
```

Now, for integrating scDist with miloDE I want to use subsets with only a few cells.:
´´´
meta.data = colData(current.sce)[, c("disease", "donor_id")] %>% as.data.frame
meta.data$cell_type <- "dummy.celltype"
out <- scDist(as.matrix(logcounts(current.sce)),meta.data,fixed.effects = "disease",
              random.effects="donor_id",
              clusters="cell_type",
              d = 5)
out$results
###  dummy.celltype 10.05632            0       19.05864 0.3338167
´´´ 
The object `current.sce` was determined as a neighborhood calculated by miloR and checked by default checks in miloDE. It contains 31 cells.
I noted, that in all cases the lower 95% CI was 0. Am I doing something wrong?
And I discovered that different numbers of PCs give quite different results, therefore my question about determining the ideal number.

Do you think this is a possible use-case?

Thank you already for any help,
Max

**Comment by phillipnicol** [comment]
To answer the first question, `scDist` performs PCA at the cell-type level, so the results will not change if you include the all cell types or just subset to one particular cell type. The only reason that the numbers are slightly different is that the distance is computed with Monte Carlo samples. 

In your particular dataset how many donors are there? When I follow the link it looks like 9 but wasn't sure if the healthy and controls are being merged together in one group. When there are a very small number of donors (<10) there can be a lot of uncertainty in the mixed model estimates which results in intervals that overlap 0 as you noticed. In this case you can try treating donor as a fixed effect. I tried this on the Demo dataset by running 

`out <- scDist(data$Y,data$meta.data,fixed.effects = c("response","patient"),
              clusters="clusters")`

The correlation with the ground truth was only slightly worse than the mixed model, but with even fewer patients it might perform better. 


In your case with 31 cells, the maximum number of PCs (with non-zero variance explained) would be 30... what happens if you set `d=30`, does it produce an error? It seems like in this application choosing a full PCA could remove the ambiguity of selecting the number of PCs... Beyond this, I would propose always setting `d` to be larger than the total number of donors, since when the model is correctly specified this is the number that you need to get accurate estimates (see page 15 of our biorxiv manuscript). Another diagnostic tool is a plot that I sometimes use is `plotBetas`, which allows you to see the effect size for each PC (example on Demo data attached below). It could be that when `d=5` you are missing some relevant information that is captured by the later PCs. 

`scDist::plotBetas(out, cluster="a")`
<img width="1499" alt="Screenshot 2024-05-16 at 9 15 35 AM" src="https://github.com/phillipnicol/scDist/assets/43178367/9b7e78d7-d1fe-4eaf-8619-a4b3d2136d7d">


Hope this helps!

Phillip
